
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

ignored = [
  "github.com/knative/serving/sample/grpc-ping*",
]

required = [
  "k8s.io/client-go/tools/cache",
]

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/errors"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/loads"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/runtime"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/spec"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/strfmt"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/swag"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/validate"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.3.0"

[[constraint]]
  name = "github.com/tylerb/graceful"
  version = "1.2.15"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.3"

[[constraint]]
  name = "github.com/streadway/amqp"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[[constraint]]
  name = "github.com/casbin/casbin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/knative/serving"
  # HEAD as of 2018-10-26
  revision = "cda99cffb47d77aacbaaddf9c7e8532f6bfe1dd2"

[[override]]
  name = "github.com/knative/build"
  # HEAD as of 2018-10-26
  revision = "47e45d6af31266829e0eb362f0f250e70e041a63"

[[override]]
  name = "github.com/knative/pkg"
  # HEAD as of 2018-10-26
  revision = "5c809f170b42301a276080f4fd884a30188ca1a5"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.3"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.3"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.3"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.11.3"

