apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  namespace: {{ .Release.Namespace }}
  annotations:
    # Use https://index.docker.io/v1/ for dockerhub
    build.knative.dev/docker-0: {{ .Values.registry.url }}
type: kubernetes.io/basic-auth
data:
  username: {{ if .Values.registry.username }}{{ .Values.registry.username | b64enc }}{{ end }}
  password: {{ if .Values.registry.password }}{{ .Values.registry.password | b64enc }}{{ end }}