apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}-service-account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dispatch-build
secrets:
- name: basic-user-pass