apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  organization: {{ .Values.global.organization }}
  config.json: |-
    {
      "registry": {
        "uri": "{{ default .Values.global.registry.uri .Values.registry.uri }}",
        "auth": "{{ default .Values.global.registry.auth .Values.registry.auth }}"
      }
    }
